orbs:
  node: circleci/node@5.1.1

version: 2.1

parameters:
  node_version:
    type: string
    default: "18.18.0"

commands:
  install_deps:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
          app-dir: ~/repo

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn build
      - run: yarn test
      - run: yarn lint:ci
      - run: yarn lint:size
